#!/bin/sh
set -eu

# 4-GPU 5k-step adaptive cascade run.
# MAX_WALLCLOCK_SECONDS=0 disables the cap for exploratory runs.
# Set MAX_WALLCLOCK_SECONDS to a positive value only for final submission runs.

export RUN_ID="${RUN_ID:-adaptive_cascade_4gpu_5k}"
export DATA_PATH="${DATA_PATH:-./data/datasets/fineweb10B_sp1024/}"
export TOKENIZER_PATH="${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model}"
export VOCAB_SIZE="${VOCAB_SIZE:-1024}"
export ITERATIONS="${ITERATIONS:-5000}"
export TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-524288}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-524288}"
export TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-200}"
export VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-500}"
export ADAPTIVE_EVAL_ENABLED="${ADAPTIVE_EVAL_ENABLED:-1}"
export ADAPTIVE_EVAL_DENSE_EVERY="${ADAPTIVE_EVAL_DENSE_EVERY:-100}"
export ADAPTIVE_EVAL_BAND_CENTER_STEP="${ADAPTIVE_EVAL_BAND_CENTER_STEP:-2500}"
export ADAPTIVE_EVAL_BAND_RADIUS_STEPS="${ADAPTIVE_EVAL_BAND_RADIUS_STEPS:-750}"
export ADAPTIVE_EVAL_FLATTEN_WINDOW="${ADAPTIVE_EVAL_FLATTEN_WINDOW:-3}"
export ADAPTIVE_EVAL_FLATTEN_RATIO="${ADAPTIVE_EVAL_FLATTEN_RATIO:-0.350}"
export ADAPTIVE_EVAL_MIN_REMAINING_FRACTION="${ADAPTIVE_EVAL_MIN_REMAINING_FRACTION:-0.2}"
export CASCADE_ENABLED="${CASCADE_ENABLED:-1}"
export QAT_ENABLED="${QAT_ENABLED:-0}"
export EMA_DECAY="${EMA_DECAY:-0.997}"
export MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-0}"

mkdir -p logs

torchrun --standalone --nproc_per_node="${NPROC_PER_NODE:-4}" train_gpt.py 2>&1 | tee "logs/${RUN_ID}.console.log"
