#!/bin/sh
set -eu

# 4-GPU 5k-step adaptive cascade run.
# MAX_WALLCLOCK_SECONDS=0 disables the cap for exploratory runs.
# Set MAX_WALLCLOCK_SECONDS to a positive value only for final submission runs.

RUN_ID="${RUN_ID:-adaptive_cascade_4gpu_5k}" \
DATA_PATH="${DATA_PATH:-./data/datasets/fineweb10B_sp1024/}" \
TOKENIZER_PATH="${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model}" \
VOCAB_SIZE="${VOCAB_SIZE:-1024}" \
ITERATIONS="${ITERATIONS:-5000}" \
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-524288}" \
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-524288}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-200}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-500}" \
ADAPTIVE_EVAL_ENABLED="${ADAPTIVE_EVAL_ENABLED:-1}" \
ADAPTIVE_EVAL_DENSE_EVERY="${ADAPTIVE_EVAL_DENSE_EVERY:-100}" \
ADAPTIVE_EVAL_BAND_CENTER_STEP="${ADAPTIVE_EVAL_BAND_CENTER_STEP:-2500}" \
ADAPTIVE_EVAL_BAND_RADIUS_STEPS="${ADAPTIVE_EVAL_BAND_RADIUS_STEPS:-750}" \
ADAPTIVE_EVAL_FLATTEN_WINDOW="${ADAPTIVE_EVAL_FLATTEN_WINDOW:-3}" \
ADAPTIVE_EVAL_FLATTEN_RATIO="${ADAPTIVE_EVAL_FLATTEN_RATIO:-0.350}" \
ADAPTIVE_EVAL_MIN_REMAINING_FRACTION="${ADAPTIVE_EVAL_MIN_REMAINING_FRACTION:-0.2}" \
CASCADE_ENABLED="${CASCADE_ENABLED:-1}" \
QAT_ENABLED="${QAT_ENABLED:-0}" \
EMA_DECAY="${EMA_DECAY:-0.997}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-0}" \
torchrun --standalone --nproc_per_node="${NPROC_PER_NODE:-4}" train_gpt.py 2>&1 | tee "logs/${RUN_ID}.console.log"
