#!/bin/sh
set -eu

RUN_ID="${RUN_ID:-adaptive_cascade_smoke_1gpu}" \
DATA_PATH="${DATA_PATH:-./data/datasets/fineweb10B_sp1024/}" \
TOKENIZER_PATH="${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model}" \
VOCAB_SIZE="${VOCAB_SIZE:-1024}" \
ITERATIONS="${ITERATIONS:-200}" \
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-32768}" \
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-8192}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-20}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-50}" \
ADAPTIVE_EVAL_ENABLED="${ADAPTIVE_EVAL_ENABLED:-1}" \
ADAPTIVE_EVAL_DENSE_EVERY="${ADAPTIVE_EVAL_DENSE_EVERY:-25}" \
ADAPTIVE_EVAL_BAND_CENTER_STEP="${ADAPTIVE_EVAL_BAND_CENTER_STEP:-100}" \
ADAPTIVE_EVAL_BAND_RADIUS_STEPS="${ADAPTIVE_EVAL_BAND_RADIUS_STEPS:-50}" \
ADAPTIVE_EVAL_FLATTEN_WINDOW="${ADAPTIVE_EVAL_FLATTEN_WINDOW:-2}" \
ADAPTIVE_EVAL_FLATTEN_RATIO="${ADAPTIVE_EVAL_FLATTEN_RATIO:-0.5}" \
ADAPTIVE_EVAL_MIN_REMAINING_FRACTION="${ADAPTIVE_EVAL_MIN_REMAINING_FRACTION:-0.3}" \
CASCADE_ENABLED="${CASCADE_ENABLED:-1}" \
QAT_ENABLED="${QAT_ENABLED:-1}" \
EMA_DECAY="${EMA_DECAY:-0.997}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-0}" \
torchrun --standalone --nproc_per_node="${NPROC_PER_NODE:-1}" train_gpt.py
